language: node_js

node_js:
  - 'node'
env:
  matrix:
    - BROWSER=chrome  BVER=stable

before_script:
  - npm install
  - ./node_modules/travis-multirunner/setup.sh
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  #- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/cucumber_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb-run -- :99 -ac -screen 0 1600x1200x16

script:
  - npm test